name: test

on:
  push:
  pull_request:
  schedule:
    - cron: "51 3 * * 6" # Runs at 03:51, only on Saturday
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - if: matrix.os == 'ubuntu'
        run: sudo apt-get install -y libgtk-4-dev
      - if: matrix.os == 'macos'
        run: brew install gtk4 gobject-introspection
      - name: Install dependencies
        run: shards install --without-development --release
      - name: Run gi-crystal
        run: bin/gi-crystal
      - name: Run specs
        run: crystal spec
